config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'registration' => 'users#new'
  post 'registration' => 'users#create'
  get 'activate/:id' => 'users#activate', as: 'activate_user'
  resources :password_resets

  get 'dashboard' => 'dashboard#index'

  root to: 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["crypted_password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["crypted_password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["crypted_password"] }
  validates :email, uniqueness: true, presence: true, if: -> { new_record? || changes["crypted_password"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def not_authenticated
    redirect_to login_path, alert: 'Please login first'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login

  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])

    @user.deliver_reset_password_instructions! if @user

    redirect_to(login_path, notice: 'Instructions have been sent to your email.')
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      return not_authenticated, alert: 'Invalid token'
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      return not_authenticated, alert: 'Invalid token'
    end

    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      redirect_to(login_path, notice: 'Password was successfully updated.')
    else
      render action: :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:user][:email], params[:user][:password])
      redirect_back_or_to(dashboard_path, notice: 'Login successful')
    else
      @user = User.new
      flash.now[:alert] = 'Invalid user/email combination'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to login_path, notice: 'Logged out successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, alert: 'You will receive an email within the next few minutes with a link to activate your account.'
    else
      render action: :new
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(login_path, notice: 'Your account was successfully activated.')
    else
      redirect_to login_path, notice: 'Please login.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(text, path, options = {})
    li_options = current_page?(path) ? { class: "active" } : {}
    content_tag(:li, li_options) do
      link_to text, path, options
    end
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when 'success'
        'alert-success'
      when 'error'
        'alert-danger'
      when 'alert'
        'alert-warning'
      when 'notice'
        'alert-success'
      else
        flash_type.to_s
    end
  end
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<p>Try to access to dashboard when not logged in!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="Sorcery gem example">
        <meta name="author" content="pama">
        <title>Sorcery Example</title>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Sorcery Example</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            <% if logged_in? %>
                <%= nav_link('Log Out', logout_path, method: :delete) %>
            <% else %>
              <%= nav_link('Log In', login_path) %>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->
    </body>
</html>
</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>

<%= simple_form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <div class="form-inputs">
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="forms-actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password?</h1>

<%= simple_form_for @user, url: password_resets_path do |f| %>
    <%= render 'shared/messages' %>

    <div class="form-inputs">
      <%= f.input :email %>
    </div>

    <div class="forms-actions">
      <%= f.submit "Reset my password!", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in" role= "alert">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Registration</h1>

<%= simple_form_for @user, url: registration_path do |f| %>
  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="forms-actions">
    <%= f.submit "Register", class: 'btn btn-primary' %>
  </div>
<% end %>